service: web-api

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: results
          method: post
          cors: true

  getAll:
    handler: handler.getAll
    events:
     - http:
         path: results
         method: get
         cors: true

  get:
    handler: handler.get
    events:
     - http:
         path: results/{query}
         method: get
         cors: true         

plugins:
  - serverless-offline

package:
  exclude:
    - venv/**
  excludeDevDependencies: true